name: mvpstarter
description: Aplicación interna de MVPStarter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.1.26

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/logo_mvpstarter.png
      - assets/icon_facebook.png
      - assets/icon_google.png